<?php
    $title = "Marmitas da Dona Rita";
    $desenvolvedor = "Renato Rodrigues Neto";

    $tutoriais = array(
        0 => array('id'=>'1', 
            'titulo'=>'Marmita Caseira nº 1',  
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Strogonoff de Frango, Batata Palha',
            'imagem'=>'img/foto2.jpg', 
            'title_img'=>'Marmita Caseira nº 1'),
        1 => array('id'=>'2', 
            'titulo'=>'Marmita Caseira nº 2',  
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Omelete de Queijo e Presunto',
            'imagem'=>'img/foto3.jpeg', 
            'title_img'=>'Marmita Caseira nº 2'),
        2 => array('id'=>'3', 
            'titulo'=>'Marmita Caseira nº 3', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Filé de Frango, Batata Frita',
            'imagem'=>'img/foto4.jpg', 
            'title_img'=>'Marmita Caseira nº 3'),
        3 => array('id'=>'4', 
            'titulo'=>'Marmita Caseira nº 4', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Bisteca, Farofa e Salada',
            'imagem'=>'img/foto5.jpg', 
            'title_img'=>'Marmita Caseira nº 4'),
        4 => array('id'=>'5', 
            'titulo'=>'Marmita Caseira nº 5', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Parmegiana de Frango, Fritas',
            'imagem'=>'img/foto6.jpg', 
            'title_img'=>'Marmita Caseira nº 5'),
        5 => array('id'=>'6', 
            'titulo'=>'Marmita Caseira nº 6', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Picanha, Fritas e Salada',
            'imagem'=>'img/foto7.jpg', 
            'title_img'=>'Marmita Caseira nº 6'),
        6 => array('id'=>'7', 
            'titulo'=>'Marmita Caseira nº 7', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Camarão, Fritas',
            'imagem'=>'img/foto8.png', 
            'title_img'=>'Marmita Caseira nº 7'),
        7 => array('id'=>'8', 
            'titulo'=>'Marmita Caseira nº 8', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Carne de Porco, Couve e Salada',
            'imagem'=>'img/foto9.jpg', 
            'title_img'=>'Marmita Caseira nº 8'),
    );